# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TasksForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import algorithms


class Ui_TasksForm(object):

    def __init__(self, algorithm, no_of_tasks):
        self.algorithm = algorithm
        self.no_of_tasks = no_of_tasks

    def setupUi(self, TasksForm):
        TasksForm.setObjectName("TasksForm")
        TasksForm.resize(745, 452)
        self.Finish = QtWidgets.QPushButton(
            TasksForm, clicked=lambda: self.DrawChart())
        self.Finish.setGeometry(QtCore.QRect(250, 390, 221, 41))
        self.Finish.setObjectName("Finish")
        self.scrollArea = QtWidgets.QScrollArea(TasksForm)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 741, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 739, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LabelGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.LabelGroup.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.LabelGroup.sizePolicy().hasHeightForWidth())
        self.LabelGroup.setSizePolicy(sizePolicy)
        self.LabelGroup.setMinimumSize(QtCore.QSize(0, 50))
        self.LabelGroup.setTitle("")
        self.LabelGroup.setObjectName("LabelGroup")
        self.QuantumLabel = QtWidgets.QLabel(self.LabelGroup)
        self.QuantumLabel.setGeometry(QtCore.QRect(440, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.QuantumLabel.setFont(font)
        self.QuantumLabel.setObjectName("QuantumLabel")

        self.TaskLabel = QtWidgets.QLabel(self.LabelGroup)
        self.TaskLabel.setGeometry(QtCore.QRect(10, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.TaskLabel.setFont(font)
        self.TaskLabel.setObjectName("TaskLabel")
        self.BurstLabel = QtWidgets.QLabel(self.LabelGroup)
        self.BurstLabel.setGeometry(QtCore.QRect(200, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BurstLabel.setFont(font)
        self.BurstLabel.setObjectName("BurstLabel")
        self.ArrivalLabel = QtWidgets.QLabel(self.LabelGroup)
        self.ArrivalLabel.setGeometry(QtCore.QRect(70, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ArrivalLabel.setFont(font)
        self.ArrivalLabel.setObjectName("ArrivalLabel")
        self.PriorityLabel = QtWidgets.QLabel(self.LabelGroup)
        self.PriorityLabel.setEnabled(True)
        self.PriorityLabel.setGeometry(QtCore.QRect(320, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PriorityLabel.setFont(font)
        self.PriorityLabel.setObjectName("PriorityLabel")
        self.verticalLayout.addWidget(self.LabelGroup)
        # make a Dict of lists here to collect every entry
        ########
        self.Spinboxes = []  # each element here is a list that contain all entries for a task
        for i in range(self.no_of_tasks):
            TaskSpins = {}
            self.TasksGroup = QtWidgets.QGroupBox(
                self.scrollAreaWidgetContents)
            sizePolicy = QtWidgets.QSizePolicy(
                QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(
                self.TasksGroup.sizePolicy().hasHeightForWidth())
            self.TasksGroup.setSizePolicy(sizePolicy)
            self.TasksGroup.setMinimumSize(QtCore.QSize(0, 50))
            self.TasksGroup.setTitle("")
            self.TasksGroup.setObjectName("TasksGroup")
            self.PrioritySpin = QtWidgets.QSpinBox(self.TasksGroup)
            self.PrioritySpin.setGeometry(QtCore.QRect(320, 10, 101, 22))
            self.PrioritySpin.setObjectName("PrioritySpin")
            self.BurstSpin = QtWidgets.QSpinBox(self.TasksGroup)
            self.BurstSpin.setGeometry(QtCore.QRect(200, 10, 101, 22))
            self.BurstSpin.setObjectName("BurstSpin")
            self.T1 = QtWidgets.QLabel(self.TasksGroup)
            self.T1.setGeometry(QtCore.QRect(-10, 0, 61, 31))
            self.T1.setFrameShadow(QtWidgets.QFrame.Raised)
            self.T1.setAlignment(QtCore.Qt.AlignCenter)
            self.T1.setObjectName("T"+str(i+1))
            self.ArrivalSpin = QtWidgets.QSpinBox(self.TasksGroup)
            self.ArrivalSpin.setGeometry(QtCore.QRect(70, 10, 101, 22))
            self.ArrivalSpin.setObjectName("ArrivalSpin")
            if i == 0:
                self.QuantumSpin = QtWidgets.QSpinBox(self.TasksGroup)
                self.QuantumSpin.setGeometry(QtCore.QRect(440, 10, 101, 22))
                self.QuantumSpin.setObjectName("QuantumSpin")
            self.verticalLayout.addWidget(self.TasksGroup)
            self.scrollArea.setWidget(self.scrollAreaWidgetContents)

            # SpinBox Hiding
            if self.algorithm == "FCFS":
                self.PriorityLabel.setDisabled(True)
                self.PrioritySpin.setDisabled(True)
                self.QuantumLabel.setDisabled(True)
                self.QuantumSpin.setDisabled(True)

            if self.algorithm == "SJF":
                self.PriorityLabel.setDisabled(True)
                self.PrioritySpin.setDisabled(True)
                self.QuantumLabel.setDisabled(True)
                self.QuantumSpin.setDisabled(True)
            if self.algorithm == "SRTF":
                self.PriorityLabel.setDisabled(True)
                self.PrioritySpin.setDisabled(True)
                self.QuantumLabel.setDisabled(True)
                self.QuantumSpin.setDisabled(True)
            if self.algorithm == "P(PR)":
                self.QuantumLabel.setDisabled(True)
                self.QuantumSpin.setDisabled(True)
            if self.algorithm == "P(NONPR)":
                self.QuantumLabel.setDisabled(True)
                self.QuantumSpin.setDisabled(True)
            if self.algorithm == "RR":
                self.PriorityLabel.setDisabled(True)
                self.PrioritySpin.setDisabled(True)

            self.retranslateUi(TasksForm, "T"+str(i+1))
            QtCore.QMetaObject.connectSlotsByName(TasksForm)

            # Adding Spins into the Dict for each task
            TaskSpins["Arrival"] = self.ArrivalSpin
            TaskSpins["Burst"] = self.BurstSpin
            TaskSpins["Priority"] = self.PrioritySpin
            TaskSpins["Quantum"] = self.QuantumSpin
            # Adding This Dict to the big list that contains all spins
            self.Spinboxes.append(TaskSpins)
            ##############################################

    def DrawChart(self):
        BurstData = []
        ArrivalData = []
        PriorityData = []
        QuantumData = 0
        for element in self.Spinboxes:
            BurstData.append(element["Burst"].text())
            ArrivalData.append(element["Arrival"].text())
            PriorityData.append(element["Priority"].text())
        if self.algorithm == "RR":
            QuantumData = self.Spinboxes[0]["Quantum"].text()

        algorithms.execute(self.algorithm, self.no_of_tasks,
                           BurstData, ArrivalData, PriorityData, int(QuantumData))

        # print(self.Spinboxes)
        print(self.algorithm)
        print(self.no_of_tasks)

    def retranslateUi(self, TasksForm, TaskName):
        _translate = QtCore.QCoreApplication.translate
        TasksForm.setWindowTitle(_translate("TasksForm", "Form"))
        self.Finish.setText(_translate("TasksForm", "Draw Gantt Chart"))
        self.QuantumLabel.setText(_translate("TasksForm", "Quantum"))
        self.TaskLabel.setText(_translate("TasksForm", "Task"))
        self.BurstLabel.setText(_translate("TasksForm", "Burst Time"))
        self.ArrivalLabel.setText(_translate("TasksForm", "Arrival Time"))
        self.PriorityLabel.setText(_translate("TasksForm", "Priority"))

        self.T1.setText(_translate("TasksForm", TaskName))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     TasksForm = QtWidgets.QWidget()
#     ui = Ui_TasksForm()
#     ui.setupUi(TasksForm)
#     TasksForm.show()
#     sys.exit(app.exec_())
